In [1]:
import pandas as pd

Stage 1

🟢 Part A — Understand the Dataset

In [2]:
# 1.Load the dataset
orders = pd.read_csv('olist_orders_dataset.csv')

In [3]:
orders

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [4]:
# 2.Inspect the first 5 records
orders.head(5)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [5]:
# 3.Find the number of rows and columns
orders.shape

(99441, 8)

In [6]:
# 4.Find all columns names
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [7]:
# 5.Understand data types
orders.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [8]:
# 6.Get a complete overview
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

🟢 Part B — Missing Values & Duplicates

In [9]:
# 7.Count missing values
orders[orders.isnull()].count()

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
dtype: int64

In [10]:
# 8.Find columns with missing values
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [11]:
# 9.Find Duplicate rows
orders.duplicated().sum()

np.int64(0)

In [12]:
# 10.Check for duplicate Order IDs
orders['order_id'].duplicated().sum()

np.int64(0)

🟡 Part C — Order Status Analysis

In [13]:
# 11.Find all unique order statuses
orders['order_status'].unique()

<StringArray>
[  'delivered',    'invoiced',     'shipped',  'processing', 'unavailable',
    'canceled',     'created',    'approved']
Length: 8, dtype: str

In [14]:
# 12.Count orders by status
orders['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [15]:
# 13.Find the percentage of each order status
orders['order_status'].value_counts(normalize=True) * 100

order_status
delivered      97.020344
shipped         1.113223
canceled        0.628513
unavailable     0.612423
invoiced        0.315765
processing      0.302692
created         0.005028
approved        0.002011
Name: proportion, dtype: float64

In [16]:
# 14.Find the most common order status
orders['order_status'].index.value_counts()

0        1
1        1
2        1
3        1
4        1
        ..
99436    1
99437    1
99438    1
99439    1
99440    1
Name: count, Length: 99441, dtype: int64

🟡 Part D — Date & Time Analysis

In [17]:
# 15.Convert all five columns to Pandas datetime.
orders['order_purchase_timestamp'] = pd.to_datetime(orders['order_purchase_timestamp'])

In [18]:
orders['order_approved_at'] = pd.to_datetime(orders['order_approved_at'])

In [19]:
orders['order_delivered_carrier_date'] = pd.to_datetime(orders['order_delivered_carrier_date'])

In [20]:
orders['order_delivered_customer_date'] = pd.to_datetime(orders['order_delivered_customer_date'])

In [21]:
orders['order_estimated_delivery_date'] = pd.to_datetime(orders['order_estimated_delivery_date'])

In [22]:
# 16.Find the earliest and latest order
orders['order_purchase_timestamp'].min() # Earliest Order

Timestamp('2016-09-04 21:15:19')

In [23]:
orders['order_purchase_timestamp'].max() # latest Order

Timestamp('2018-10-17 17:30:18')

🟠 Part E — Time-Based Business Analysis

In [24]:
# 17.Find the number of orders by year
orders['Year'] = orders['order_purchase_timestamp'].dt.year

In [25]:
orders['Year'].value_counts()

Year
2018    54011
2017    45101
2016      329
Name: count, dtype: int64

In [26]:
# 18.Find the number of orders by month
orders['Month'] = orders['order_purchase_timestamp'].dt.month_name()

In [27]:
orders['Month'].value_counts()

Month
August       10843
May          10573
July         10318
March         9893
June          9412
April         9343
February      8508
January       8069
November      7544
December      5674
October       4959
September     4305
Name: count, dtype: int64

In [28]:
# 19.Find the busiest day of the week
orders['Date'] = orders['order_purchase_timestamp'].dt.day_name()

In [29]:
orders['Date'].value_counts().head(1)

Date
Monday    16196
Name: count, dtype: int64

In [30]:
# 20.Compare estimated vs actual delivery
orders['order_delivered_customer_date'] = pd.to_datetime(
    orders['order_delivered_customer_date']
)

orders['order_estimated_delivery_date'] = pd.to_datetime(
    orders['order_estimated_delivery_date']
)

In [31]:
orders['order_delivered_customer_date'] > orders['order_estimated_delivery_date']

0        False
1        False
2        False
3        False
4        False
         ...
99436    False
99437    False
99438    False
99439    False
99440    False
Length: 99441, dtype: bool

In [32]:
import numpy as np

In [33]:
orders['delivery_status'] = np.where(
    orders['order_delivered_customer_date'] > orders['order_estimated_delivery_date'],
    'Late',
    'On Time'
)

In [34]:
orders[['order_delivered_customer_date',
        'order_estimated_delivery_date',
        'delivery_status']].head(10)

  order_delivered_customer_date order_estimated_delivery_date delivery_status
0           2017-10-10 21:25:13                    2017-10-18         On Time
1           2018-08-07 15:27:45                    2018-08-13         On Time
2           2018-08-17 18:06:29                    2018-09-04         On Time
3           2017-12-02 00:28:42                    2017-12-15         On Time
4           2018-02-16 18:17:02                    2018-02-26         On Time
5           2017-07-26 10:57:55                    2017-08-01         On Time
6                           NaT                    2017-05-09         On Time
7           2017-05-26 12:55:51                    2017-06-07         On Time
8           2017-02-02 14:08:10                    2017-03-06         On Time
9           2017-08-16 17:14:30                    2017-08-23         On Time

In [35]:
# i).How many were late?
orders['delivery_status'].value_counts()

delivery_status
On Time    91614
Late        7827
Name: count, dtype: int64

In [36]:
# ii).What percentage were late?
orders['delivery_status'].value_counts(normalize=True) * 100

delivery_status
On Time    92.129001
Late        7.870999
Name: proportion, dtype: float64

🟡 Stage 2 — Customers + Orders

In [37]:
# 21.Load the customers dataset
customers = pd.read_csv('olist_customers_dataset.csv')

In [38]:
customers

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [39]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [40]:
# i).How man rows and columns does customers have?
customers.shape

(99441, 5)

In [41]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [42]:
# ii).What are the column names?
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

In [43]:
# iii).Which columns contain missing values?
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [44]:
# iv).1. How many unique customer_unique_id values are there?
customers['customer_unique_id'].unique()

<StringArray>
['861eff4711a542e4b93843c6dd7febb0', '290c77bc529b7ac935b93aa66c333dc3',
 '060e732b5b29e8181a18229c7b0b2b5e', '259dac757896d24d7702b9acbbff3f3c',
 '345ecd01c38d18a9036ed96c73b8d066', '4c93744516667ad3b8f1fb645a3116a4',
 'addec96d2e059c80c30fe6871d30d177', '57b2a98a409812fe9618067b6b8ebe4f',
 '1175e95fb47ddff9de6b2b06188f7e0d', '9afe194fb833f79e300e37e580171f22',
 ...
 'ca186065de6e2d01cfc99763e6d62048', 'd111b06b6f3a2add0d2241325f65b5ca',
 'e7f8760e2bbd2f1986bebd99596c088e', 'b3e53d18a997f27a3ffd16da497eaf58',
 '4b5820135d360a45552b5163835b1d89', '1a29b476fee25c95fbafc67c5ac95cf8',
 'd52a67c98be1cf6a5c84435bd38d095d', 'e9f50caf99f032f0bf3c55141f019d99',
 '73c2643a0a458b49f58cea58833b192e', '84732c5050c01db9b23e19ba39899398']
Length: 96096, dtype: str

In [45]:
# 22.Understand the customer IDs
customers['customer_id'].nunique()

99441

In [46]:
customers['customer_unique_id'].nunique()

96096

In [47]:
# Check customer locations
# Find the number of unique:
# - states
# - cities
# - ZIP-code prefixes
customers['customer_state'].nunique()

27

In [48]:
customers['customer_city'].nunique()

4119

In [49]:
customers['customer_zip_code_prefix'].nunique()

14994

In [50]:
# 24.Find customers by state
customers['customer_state'].value_counts()

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
Name: count, dtype: int64

In [51]:
# 25.Merge orders and customers
orders_customers = orders.merge(customers,on='customer_id',how='left')

In [52]:
orders_customers.shape

(99441, 16)

In [53]:
orders_customers.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,Year,Month,Date,delivery_status,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,2017,October,Monday,On Time,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,2018,July,Tuesday,On Time,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,2018,August,Wednesday,On Time,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,2017,November,Saturday,On Time,7c142cf63193a1473d2e66489a9ae977,59296,sao goncalo do amarante,RN
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2018,February,Tuesday,On Time,72632f0f9dd73dfee390c9b22eb56dd6,9195,santo andre,SP

In [54]:
# 26.Find orders by state
orders_customers['customer_state'].value_counts()

customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
SE      350
TO      280
RO      253
AM      148
AC       81
AP       68
RR       46
Name: count, dtype: int64

In [55]:
# 27.Find the top 10 cities by orders
orders_customers.groupby('customer_city')['order_id'].count().sort_values(ascending=False).head(10)

customer_city
sao paulo                15540
rio de janeiro            6882
belo horizonte            2773
brasilia                  2131
curitiba                  1521
campinas                  1444
porto alegre              1379
salvador                  1245
guarulhos                 1189
sao bernardo do campo      938
Name: order_id, dtype: int64

In [56]:
# 28.Find unique customers who ordered
orders_customers['customer_unique_id'].nunique()

96096

In [57]:
# 29.Find repeat customers
customer_orders = (orders_customers.groupby('customer_unique_id')['order_status'].count())

In [58]:
repeat_customers = customer_orders[customer_orders > 1]
repeat_customers

customer_unique_id
00172711b30d52eea8b313a7f2cced02    2
004288347e5e88a27ded2bb23747066c    2
004b45ec5c64187465168251cd1c9c2f    2
0058f300f57d7b93c477a131a59b36c3    2
00a39521eb40f7012db50455bf083460    2
                                   ..
ff36be26206fffe1eb37afd54c70e18b    3
ff44401d0d8f5b9c54a47374eb48c1b8    2
ff8892f7c26aa0446da53d01b18df463    2
ff922bdd6bafcdf99cb90d7f39cea5b3    3
ffe254cc039740e17dd15a5305035928    2
Name: order_status, Length: 2997, dtype: int64

In [59]:
# 30.Percentage of repeat customers
repeat_percentage = (
    orders_customers
    .groupby('customer_unique_id')['order_id']
    .count()
    .gt(1)
    .mean()
    * 100
)

repeat_percentage

np.float64(3.1187562437562435)

🟠 Stage 3 — Products & Sales

In [60]:
# 31.Load dataset
order_items = pd.read_csv('olist_order_items_dataset.csv')

In [61]:
order_items.shape

(112650, 7)

In [62]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [63]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

In [64]:
# i).Number of rows
order_items.loc[:]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [65]:
# ii).Number of columns
len(order_items.columns)

7

In [66]:
# iii).Column names
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')

In [67]:
# iv).Missing Values
order_items.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [68]:
# v).Number of unique orders
order_items['order_id'].nunique()

98666

In [69]:
# vi).Number of unique products
order_items['product_id'].nunique()

32951

In [70]:
# 32.Understand the relationship
# Why can one order_id appear multiple times in order_items
order_items['order_id'].value_counts().head()

order_id
8272b63d03f5f79c56e9e4120aec44ef    21
1b15974a0141d54e36626dca3fdc731a    20
ab14fdcfbe524636d65ee38360e22ce8    20
428a2f660dc84138d969ccd69a0ab6d5    15
9ef13efd6949e4573a18964dd1bbe7f5    15
Name: count, dtype: int64

In [71]:
# 33.Calculate total product revenue
order_items['price'].sum()

np.float64(13591643.7)

In [72]:
# 34.Calculate total freight cost
order_items['freight_value'].sum()

np.float64(2251909.54)

In [73]:
# i).Total amount paid for products + freight
total_amount = (
    order_items['price'] + order_items['freight_value']
).sum()

total_amount

np.float64(15843553.24)

In [74]:
# 35.Find the average product price
order_items['Average'] = order_items['price'].mean()

In [75]:
order_items['Median'] = order_items['price'].median()

In [76]:
order_items[['Average','Median']].sum()

Average    13591643.7
Median      8447623.5
dtype: float64

🟠 Product Analysis

In [77]:
# 36.Load products
products = pd.read_csv('olist_products_dataset.csv')

In [78]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [79]:
products.shape

(32951, 9)

In [80]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [81]:
# i).Number of products
products.shape

(32951, 9)

In [82]:
# ii).Unique product_id
products['product_id'].nunique()

32951

In [83]:
# iii)Missing Values
products.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [84]:
# 37.Merge order_items + products
items_products = order_items.merge(products,on='product_id',how='left')

In [85]:
items_products.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,Average,Median,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,120.653739,74.99,cool_stuff,58.0,598.0,4.0,650.0,28.0,9.0,14.0
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,120.653739,74.99,pet_shop,56.0,239.0,2.0,30000.0,50.0,30.0,40.0
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,120.653739,74.99,moveis_decoracao,59.0,695.0,2.0,3050.0,33.0,13.0,33.0
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,120.653739,74.99,perfumaria,42.0,480.0,1.0,200.0,16.0,10.0,15.0
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,120.653739,74.99,ferramentas_jardim,59.0,409.0,1.0,3750.0,35.0,40.0,30.0

In [86]:
items_products.shape

(112650, 17)

In [87]:
# 38.Top 10 categories by quantity
top_categories_quantity = items_products.groupby('product_category_name').size().sort_values(ascending=False).head(10)
top_categories_quantity

product_category_name
cama_mesa_banho           11115
beleza_saude               9670
esporte_lazer              8641
moveis_decoracao           8334
informatica_acessorios     7827
utilidades_domesticas      6964
relogios_presentes         5991
telefonia                  4545
ferramentas_jardim         4347
automotivo                 4235
dtype: int64

In [88]:
# 39.Find the top 10 product categories by revenue
top_categories_revenue = items_products.groupby('product_category_name')['price'].sum().sort_values(ascending=False).head(10)
top_categories_revenue

product_category_name
beleza_saude              1258681.34
relogios_presentes        1205005.68
cama_mesa_banho           1036988.68
esporte_lazer              988048.97
informatica_acessorios     911954.32
moveis_decoracao           729762.49
cool_stuff                 635290.85
utilidades_domesticas      632248.66
automotivo                 592720.11
ferramentas_jardim         485256.46
Name: price, dtype: float64

In [89]:
# 40.Business Question
# Compare 
print("Top categories by quantity:")
print(top_categories_quantity)

print("\nTop categories by revenue:")
print(top_categories_revenue)

Top categories by quantity:
product_category_name
cama_mesa_banho           11115
beleza_saude               9670
esporte_lazer              8641
moveis_decoracao           8334
informatica_acessorios     7827
utilidades_domesticas      6964
relogios_presentes         5991
telefonia                  4545
ferramentas_jardim         4347
automotivo                 4235
dtype: int64

Top categories by revenue:
product_category_name
beleza_saude              1258681.34
relogios_presentes        1205005.68
cama_mesa_banho           1036988.68
esporte_lazer              988048.97
informatica_acessorios     911954.32
moveis_decoracao           729762.49
cool_stuff                 635290.85
utilidades_domesticas      632248.66
automotivo                 592720.11
ferramentas_jardim         485256.46
Name: price, dtype: float64

🔵 Stage 4 — Payments & Reviews

In [90]:
payments = pd.read_csv('olist_order_payments_dataset.csv')

In [91]:
# Inspect
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [92]:
payments.shape

(103886, 5)

In [93]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [94]:
# i).Number of rows
payments.loc[:]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45
...,...,...,...,...,...
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [95]:
# ii).Number of columns
payments.columns

Index(['order_id', 'payment_sequential', 'payment_type',
       'payment_installments', 'payment_value'],
      dtype='str')

In [96]:
# iii).Missing Values
payments.isnull().sum()

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

In [97]:
# iv).Unique orders
payments['order_id'].nunique()

99440

In [98]:
# v).Unique payment types
payments['payment_type'].nunique()

5

In [143]:
# 42.Understand payment methods
payments['payment_type'].value_counts(normalize=True).mul(100).round(2)

payment_type
credit_card    73.92
boleto         19.04
voucher         5.56
debit_card      1.47
not_defined     0.00
Name: proportion, dtype: float64

In [100]:
# 43.Analyze payment installments
payments['payment_installments'].value_counts().sort_index()

payment_installments
0         2
1     52546
2     12413
3     10461
4      7098
5      5239
6      3920
7      1626
8      4268
9       644
10     5328
11       23
12      133
13       16
14       15
15       74
16        5
17        8
18       27
20       17
21        3
22        1
23        1
24       18
Name: count, dtype: int64

In [144]:
round(payments['payment_installments'].mean(), 2)

np.float64(2.85)

In [102]:
# 44.Load the reviews dataset
reviews = pd.read_csv('olist_order_reviews_dataset.csv')

In [103]:
# Inspect
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [104]:
reviews.shape

(99224, 7)

In [105]:
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

In [145]:
# i).Number of reviews
reviews['review_id'].shape[0]

99224

In [107]:
# ii).Missing Values
reviews.isna().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [108]:
# iii).Unique orders
reviews['order_id'].nunique()

98673

In [109]:
# iii).Distribution of review-score
reviews['review_score'].describe()

count    99224.000000
mean         4.086421
std          1.347579
min          1.000000
25%          4.000000
50%          5.000000
75%          5.000000
max          5.000000
Name: review_score, dtype: float64

In [110]:
# 45.Analyze review scores
reviews['review_score'].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [111]:
# Average review score
reviews['review_score'].mean()

np.float64(4.08642062404257)

In [146]:
# 46.Review score percentage
reviews['review_score'].value_counts(normalize=True).sort_index().mul(100).round(2)

review_score
1    11.51
2     3.18
3     8.24
4    19.29
5    57.78
Name: proportion, dtype: float64

In [113]:
# 47.Merge Orders + Reviews
order_reviews = orders.merge(reviews,on='order_id',how='left')

In [114]:
order_reviews.groupby('order_status')['review_score'].mean()
# Do different order statuses have different average review scores?
# YES

order_status
approved       2.500000
canceled       1.811166
created        2.333333
delivered      4.155717
invoiced       1.661342
processing     1.277027
shipped        2.008629
unavailable    1.530988
Name: review_score, dtype: float64

In [163]:
# 48.Delivery Time vs Review Score
# Step 1 — Convert dates
orders['order_purchase_timestamp'] = pd.to_datetime(
    orders['order_purchase_timestamp']
)

orders['order_delivered_customer_date'] = pd.to_datetime(
    orders['order_delivered_customer_date']
)

In [164]:
# Step 2 — Calculate delivery days
orders['delivery_days'] = (orders['order_delivered_customer_date'] - orders['order_purchase_timestamp']).dt.days

In [158]:
orders[['order_purchase_timestamp','order_delivered_customer_date','delivery_days']].head()

  order_purchase_timestamp order_delivered_customer_date  delivery_days
0      2017-10-02 10:56:33           2017-10-10 21:25:13            8.0
1      2018-07-24 20:41:37           2018-08-07 15:27:45           13.0
2      2018-08-08 08:38:49           2018-08-17 18:06:29            9.0
3      2017-11-18 19:28:06           2017-12-02 00:28:42           13.0
4      2018-02-13 21:18:39           2018-02-16 18:17:02            2.0

In [165]:
# Step 3 — Merge with reviews
orders_delivery_reviews = orders.merge(reviews,on='order_id',how='left')

In [166]:
# Step 4 — Remove missing delivery days
delivery_reviews = orders_delivery_reviews.dropna(
    subset=['delivery_days', 'review_score']
).copy()

In [167]:
# Step 5 — Create delivery groups
delivery_reviews['delivery_group'] = pd.cut(
    delivery_reviews['delivery_days'],
    bins=[-1, 3, 7, 14, float('inf')],
    labels=['0-3 days', '4-7 days', '8-14 days', '15+ days']
)

In [168]:
delivery_reviews['delivery_group'].value_counts()

delivery_group
8-14 days    36396
15+ days     26278
4-7 days     25089
0-3 days      8596
Name: count, dtype: int64

In [169]:
# Step 6 — Average review score
delivery_reviews.groupby(
    'delivery_group',
    observed=True
)['review_score'].mean().round(2)

delivery_group
0-3 days     4.46
4-7 days     4.39
8-14 days    4.29
15+ days     3.65
Name: review_score, dtype: float64

In [121]:
# 49.Payment Type vs Review Score
payments_reviews = payments.merge(reviews, on='order_id',how='left')

In [171]:
# Average review score by payment type
payments_reviews.groupby('payment_type')['review_score'].mean().round(2)

payment_type
boleto         4.09
credit_card    4.09
debit_card     4.17
not_defined    1.67
voucher        4.00
Name: review_score, dtype: float64

In [172]:
# Number of reviews/orders by payment type
payments_reviews.groupby(
    'payment_type'
)['review_score'].count().sort_values(ascending=False)

payment_type
credit_card    76600
boleto         19762
voucher         5783
debit_card      1529
not_defined        3
Name: review_score, dtype: int64

In [179]:
# Better version — both together
payment_analysis = (
    payments_reviews
    .groupby('payment_type')
    .agg(
        reviews=('review_score', 'count'),
        average_rating=('review_score', 'mean')
    )
    .round(2)
    .sort_values('average_rating', ascending=False)
)

payment_analysis

              reviews  average_rating
payment_type
debit_card       1529            4.17
boleto          19762            4.09
credit_card     76600            4.09
voucher          5783            4.00
not_defined         3            1.67

In [173]:
# 50.Final Business Question
# 1. Delivery time
delivery_reviews.groupby(
    'delivery_group',
    observed=True
)['review_score'].mean().round(2)

delivery_group
0-3 days     4.46
4-7 days     4.39
8-14 days    4.29
15+ days     3.65
Name: review_score, dtype: float64

In [174]:
delivery_analysis = (
    delivery_reviews
    .groupby('delivery_group', observed=True)
    .agg(
        reviews=('review_score', 'count'),
        average_rating=('review_score', 'mean')
    )
    .round(2)
)

delivery_analysis

                reviews  average_rating
delivery_group
0-3 days           8596            4.46
4-7 days          25089            4.39
8-14 days         36396            4.29
15+ days          26278            3.65

In [176]:
# 2.Payment method
payment_analysis

              reviews  average_rating
payment_type
debit_card       1529            4.17
boleto          19762            4.09
credit_card     76600            4.09
voucher          5783            4.00
not_defined         3            1.67

In [177]:
# 3. Order status
status_analysis = (
    order_reviews
    .groupby('order_status')
    .agg(
        reviews=('review_score', 'count'),
        average_rating=('review_score', 'mean')
    )
    .round(2)
    .sort_values('average_rating', ascending=False)
)

status_analysis

              reviews  average_rating
order_status
delivered       96361            4.16
approved            2            2.50
created             3            2.33
shipped          1043            2.01
canceled          609            1.81
invoiced          313            1.66
unavailable       597            1.53
processing        296            1.28

In [180]:
# 4.Product category → Review score
# Step 1 — Orders + Reviews
order_review = orders.merge(
    reviews,
    on='order_id',
    how='inner'
)

In [181]:
# Step 2 — Add order items
order_review_items = order_review.merge(
    order_items,
    on='order_id',
    how='inner'
)

In [182]:
# Step 3 — Add product information
order_review_products = order_review_items.merge(
    products,
    on='product_id',
    how='left'
)

In [183]:
# Step 4 — Average rating by category
category_reviews = (
    order_review_products
    .groupby('product_category_name')
    .agg(
        reviews=('review_score', 'count'),
        average_rating=('review_score', 'mean')
    )
    .round(2)
    .sort_values('average_rating')
)

category_reviews.head(10)

                                               reviews  average_rating
product_category_name
seguros_e_servicos                                   2            2.50
fraldas_higiene                                     39            3.26
portateis_cozinha_e_preparadores_de_alimentos       15            3.27
pc_gamer                                             9            3.33
moveis_escritorio                                 1687            3.49
casa_conforto_2                                     27            3.63
fashion_roupa_masculina                            131            3.64
telefonia_fixa                                     262            3.68
artigos_de_festas                                   43            3.77
fashion_roupa_feminina                              50            3.78